#!/usr/bin/env python3
"""
Auto-generated by skill-to-http-flash v2.0
Skill: $skill_name
Description: $skill_description
Generated: $generated_at

⚠️  This file is generated. Do not edit directly.
    Re-run `python flash.py recreate --skill $skill_name` after skill upgrades.

──────────────────────────────────────────────────────────────
flash v2.0 — subprocess 直执行
  POST /run  →  subprocess.run([interpreter, entry, --flag value, ...])
              →  unified envelope { success / exit_code / elapsed_ms /
                                    data | output / stderr / truncated }

不依赖 OpenClaw Gateway / LLM / sessions_spawn 任何链路。
"""

from __future__ import annotations

import datetime
import hmac
import ipaddress
import json
import logging
import os
import re
import shlex
import shutil
import signal
import socket
import subprocess
import sys
import threading
import time
import uuid
from contextlib import asynccontextmanager
from pathlib import Path
from typing import Any

import uvicorn
from fastapi import FastAPI, HTTPException, Request as _Request
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import HTMLResponse, JSONResponse
from pydantic import BaseModel, Field

# ============================================================
# Configuration (compiled at generation time)
# ============================================================

SKILL_NAME = $skill_name
SKILL_DESCRIPTION = $skill_description
SKILL_DIR = $skill_dir
ENTRY_REL = $entry_rel              # entry 路径（相对 skill 目录）
INTERPRETER = $interpreter          # python3 / bash / ...（默认按扩展名）
PORT = $port
DEFAULT_TIMEOUT = $timeout          # /run subprocess 超时（秒）
GENERATED_AT = $generated_at

TLS_ENABLED = bool($tls_enabled)

# Embedded SKILL.md (truncated at generation time, 仅供 /schema 展示用)
SKILL_MD = $skill_md_embedded

# Input parameter schema (JSON Schema, parsed at runtime)
_INPUT_SCHEMA_JSON = """$input_schema_json"""
INPUT_SCHEMA = json.loads(_INPUT_SCHEMA_JSON)

# 输出截断阈值
MAX_OUTPUT_BYTES = 512 * 1024  # 512 KB
MAX_STDERR_BYTES = 16 * 1024   # 16 KB（仅 fail 时透出）

# ────────────────────────────────────────────────────────────────
# 持久化根目录探测
#
# 优先级：
#   1. FLASH_DATA_DIR / OPENCLAW_FLASH_DATA_DIR / OPENCLAW_HTTP_ROOT
#   2. <workspace>/.skill-to-http-flash/ 和 <workspace>/.http/
#   3. ~/.skill-to-http-flash/ 和 ~/.http/
# 同时支持 standalone：FLASH_SKILL_DIR 覆盖 SKILL_DIR
# ────────────────────────────────────────────────────────────────
def _detect_workspace_dir(env_vars: list[str], subdir: str) -> Path:
    for env_var in env_vars:
        if env := os.environ.get(env_var):
            return Path(env).expanduser()
    workspace = os.environ.get(
        "OPENCLAW_WORKSPACE",
        str(Path.home() / ".openclaw" / "workspace"),
    )
    ws_path = Path(workspace)
    if ws_path.exists() and (ws_path / "skills").exists():
        return ws_path / subdir
    return Path.home() / subdir


FLASH_DATA_DIR = _detect_workspace_dir(
    ["FLASH_DATA_DIR", "OPENCLAW_FLASH_DATA_DIR"],
    ".skill-to-http-flash",
)
HTTP_ROOT = _detect_workspace_dir(["OPENCLAW_HTTP_ROOT"], ".http")

# Runtime override: FLASH_SKILL_DIR 可在 standalone 下覆盖 SKILL_DIR
if env_skill := os.environ.get("FLASH_SKILL_DIR"):
    SKILL_DIR = env_skill

SKILL_DIR_PATH = Path(SKILL_DIR).expanduser()
ENTRY_PATH = (SKILL_DIR_PATH / ENTRY_REL).resolve() if ENTRY_REL else None

# ────────────────────────────────────────────────────────────────
# API Key auth (X-API-Key, 沿用 skill-to-http / agent-easy-http 约定)
# ────────────────────────────────────────────────────────────────
def _load_flash_api_key() -> str:
    if env_key := os.environ.get("FLASH_API_KEY", "").strip():
        return env_key
    key_file = HTTP_ROOT / "secrets" / "api-keys" / f"flash-{SKILL_NAME}.key"
    if key_file.exists():
        try:
            return key_file.read_text().strip()
        except Exception:
            pass
    return ""


FLASH_API_KEY: str = _load_flash_api_key()
API_KEY_HEADER_NAME = "X-API-Key"

# Cert / PID / log paths
_HTTP_CERT_DIR = HTTP_ROOT / "certs" / f"flash-{SKILL_NAME}"
CERT_FILE = _HTTP_CERT_DIR / "server.crt"
KEY_FILE = _HTTP_CERT_DIR / "server.key"
_HTTP_CERT_DIR.mkdir(parents=True, exist_ok=True)

PID_FILE = FLASH_DATA_DIR / f"{SKILL_NAME}.pid"
LOG_FILE = FLASH_DATA_DIR / "logs" / f"{SKILL_NAME}.log"
LOG_FILE.parent.mkdir(parents=True, exist_ok=True)
PID_FILE.parent.mkdir(parents=True, exist_ok=True)

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
    handlers=[
        logging.StreamHandler(sys.stdout),
        logging.FileHandler(str(LOG_FILE), mode="a", encoding="utf-8"),
    ],
)
logger = logging.getLogger(f"flash.{SKILL_NAME}")

# Runtime TLS toggle
_tls_env = os.environ.get("FLASH_TLS_ENABLED", "").strip().lower()
if _tls_env in ("1", "true", "yes", "on"):
    TLS_ENABLED = True
elif _tls_env in ("0", "false", "no", "off"):
    TLS_ENABLED = False


# ============================================================
# Certificate generation (inline, openssl SAN self-signed)
# ============================================================

CERT_VALIDITY_DAYS = 365


def _get_local_ips() -> list:
    """Collect local IPs including loopback."""
    ips = [ipaddress.ip_address("127.0.0.1"), ipaddress.ip_address("::1")]
    seen = {"127.0.0.1", "::1"}
    try:
        with socket.socket(socket.AF_INET, socket.SOCK_DGRAM) as s:
            s.connect(("8.8.8.8", 80))
            ip_str = s.getsockname()[0]
            if ip_str and ip_str not in seen:
                ips.append(ipaddress.ip_address(ip_str))
                seen.add(ip_str)
    except Exception:
        pass
    try:
        hostname = socket.gethostname()
        for addr in socket.getaddrinfo(hostname, None):
            ip_str = addr[4][0].split('%')[0]
            if ip_str and ip_str not in seen:
                try:
                    ip = ipaddress.ip_address(ip_str)
                    if not ip.is_loopback:
                        ips.append(ip)
                        seen.add(ip_str)
                except ValueError:
                    pass
    except Exception:
        pass
    return ips


def _cert_is_valid() -> bool:
    if not CERT_FILE.exists() or not KEY_FILE.exists():
        return False
    try:
        from cryptography import x509
        from cryptography.hazmat.backends import default_backend
        cert_pem = CERT_FILE.read_bytes()
        cert = x509.load_pem_x509_certificate(cert_pem, default_backend())
        now = datetime.datetime.now(datetime.timezone.utc)
        return cert.not_valid_before_utc <= now <= cert.not_valid_after_utc
    except Exception:
        return False


def _cert_needs_regeneration() -> bool:
    if not _cert_is_valid():
        return True
    try:
        from cryptography import x509
        from cryptography.hazmat.backends import default_backend
        cert_pem = CERT_FILE.read_bytes()
        cert = x509.load_pem_x509_certificate(cert_pem, default_backend())
        san = cert.extensions.get_extension_for_class(x509.SubjectAlternativeName)
        cert_ips = set(str(ip) for ip in san.value.get_values_for_type(x509.IPAddress))
        current_ips = {str(ip) for ip in _get_local_ips()}
        current_ips.add("127.0.0.1")
        if not current_ips.issubset(cert_ips):
            logger.info("Certificate IPs outdated, regenerating")
            return True
    except Exception:
        return True
    return False


def _generate_cert():
    """Generate self-signed certificate (cryptography lib, with SAN)."""
    if not _cert_needs_regeneration():
        logger.info("Reusing existing valid certificate")
        return

    logger.info("Generating self-signed certificate...")
    from cryptography import x509
    from cryptography.hazmat.primitives import hashes, serialization
    from cryptography.hazmat.primitives.asymmetric import rsa
    from cryptography.hazmat.backends import default_backend
    from cryptography.x509.oid import NameOID

    private_key = rsa.generate_private_key(
        public_exponent=65537, key_size=2048, backend=default_backend()
    )

    subject = issuer = x509.Name([
        x509.NameAttribute(NameOID.COUNTRY_NAME, "CN"),
        x509.NameAttribute(NameOID.ORGANIZATION_NAME, "skill-to-http-flash"),
        x509.NameAttribute(NameOID.COMMON_NAME, "localhost"),
    ])

    san_entries = [
        x509.DNSName("localhost"),
        x509.IPAddress(ipaddress.IPv4Address("127.0.0.1")),
        x509.IPAddress(ipaddress.IPv6Address("::1")),
    ]
    for ip in _get_local_ips():
        san_entries.append(x509.IPAddress(ip))

    cert = (
        x509.CertificateBuilder()
        .subject_name(subject)
        .issuer_name(issuer)
        .public_key(private_key.public_key())
        .serial_number(x509.random_serial_number())
        .not_valid_before(datetime.datetime.now(datetime.timezone.utc))
        .not_valid_after(
            datetime.datetime.now(datetime.timezone.utc)
            + datetime.timedelta(days=CERT_VALIDITY_DAYS)
        )
        .add_extension(x509.SubjectAlternativeName(san_entries), critical=False)
        .sign(private_key, hashes.SHA256(), default_backend())
    )

    _pem_encoding = getattr(serialization, "Encoding").PEM
    KEY_FILE.write_bytes(private_key.private_bytes(
        encoding=_pem_encoding,
        format=serialization.PrivateFormat.PKCS8,
        encryption_algorithm=serialization.NoEncryption(),
    ))
    KEY_FILE.chmod(0o600)
    CERT_FILE.write_bytes(cert.public_bytes(_pem_encoding))
    logger.info(f"Certificate written to {CERT_FILE}")


# ============================================================
# Core: subprocess 直执行（v2.0 核心）
# ============================================================

class FlashError(Exception):
    """flash 自身的业务错误，包含 error_type。"""

    def __init__(self, error_type: str, message: str):
        super().__init__(message)
        self.error_type = error_type
        self.message = message


# 字段名白名单（防注入）：[a-z][a-z0-9_]*
_FIELD_NAME_RE = re.compile(r"^[a-z][a-z0-9_]*$$")  # double-dollar escapes Template subst


def _resolve_entry() -> Path:
    """解析 skill 入口（运行时再校验，以支持 FLASH_SKILL_DIR 覆盖）。

    成功返回绝对 Path；失败抛 FlashError("entry_not_found")。
    """
    if not ENTRY_REL:
        raise FlashError(
            "entry_not_found",
            "No entry configured (generation-time error). "
            "Re-run `flash.py create --skill <name>` and ensure SKILL.md "
            "has frontmatter `flash.entry: scripts/xxx.py`.",
        )
    skill_root = Path(SKILL_DIR).expanduser()
    if not skill_root.exists():
        raise FlashError(
            "entry_not_found",
            f"Skill directory not found: {skill_root}. "
            f"Set FLASH_SKILL_DIR env var if running standalone.",
        )
    entry = (skill_root / ENTRY_REL).resolve()
    if not entry.exists():
        raise FlashError(
            "entry_not_found",
            f"Entry file not found: {entry} (skill={SKILL_NAME}, "
            f"entry_rel={ENTRY_REL})",
        )
    if entry.suffix != ".py":
        raise FlashError(
            "entry_not_found",
            f"Entry must be a .py file, got: {entry}. "
            "flash v2.0 does not support shell entries; wrap your .sh in a "
            "Python script that calls subprocess.",
        )
    return entry


def _build_argv(input_dict: dict[str, Any]) -> list[str]:
    """JSON → CLI argv。

    规则：
      - 字段名 foo_bar → --foo-bar（下划线 → 横杠）
      - 字符串/数字 → ["--key", "value"]
      - True → ["--key"]
      - False / None → 不传
      - list → 重复 flag
      - dict → 序列化为 JSON 字符串
    """
    entry = _resolve_entry()
    interp = INTERPRETER or "python3"
    argv: list[str] = [interp, str(entry)]

    for key, value in input_dict.items():
        if not _FIELD_NAME_RE.match(key):
            raise FlashError(
                "validation_failed",
                f"Invalid parameter name '{key}'. "
                f"Allowed pattern: [a-z][a-z0-9_]* (lowercase, snake_case).",
            )
        flag = f"--{key.replace('_', '-')}"

        if value is None or value is False:
            continue
        if value is True:
            argv.append(flag)
            continue
        if isinstance(value, (str, int, float)):
            argv.extend([flag, str(value)])
            continue
        if isinstance(value, list):
            for item in value:
                if item is None:
                    continue
                if isinstance(item, (dict, list)):
                    argv.extend([flag, json.dumps(item, ensure_ascii=False)])
                else:
                    argv.extend([flag, str(item)])
            continue
        if isinstance(value, dict):
            argv.extend([flag, json.dumps(value, ensure_ascii=False)])
            continue
        # 兜底：转字符串
        argv.extend([flag, str(value)])

    return argv


def _run_subprocess(
    argv: list[str],
    timeout: int,
    truncate: bool = True,
) -> tuple[subprocess.CompletedProcess, bool, bool]:
    """执行 subprocess，返回 (CompletedProcess, stdout_truncated, stderr_truncated)。

    truncate=False 用于异步任务（不截断，完整保留）。
    """
    skill_root = Path(SKILL_DIR).expanduser()
    try:
        proc = subprocess.run(
            argv,
            cwd=str(skill_root),
            capture_output=True,
            timeout=timeout,
            check=False,  # exit_code != 0 不算异常，交给上层 envelope
        )
    except subprocess.TimeoutExpired as e:
        raise FlashError(
            "timeout",
            f"Subprocess timed out after {timeout}s. "
            f"Use POST /run/async for long-running tasks.",
        ) from e
    except FileNotFoundError as e:
        raise FlashError(
            "spawn_failed",
            f"Failed to spawn subprocess: {e}. "
            f"Check that '{argv[0]}' is in PATH.",
        ) from e
    except PermissionError as e:
        raise FlashError(
            "spawn_failed",
            f"Permission denied: {e}",
        ) from e
    except OSError as e:
        raise FlashError(
            "spawn_failed",
            f"OS error spawning subprocess: {e}",
        ) from e

    stdout_truncated = False
    stderr_truncated = False
    if truncate:
        if proc.stdout and len(proc.stdout) > MAX_OUTPUT_BYTES:
            proc.stdout = proc.stdout[:MAX_OUTPUT_BYTES]
            stdout_truncated = True
        if proc.stderr and len(proc.stderr) > MAX_STDERR_BYTES:
            proc.stderr = proc.stderr[:MAX_STDERR_BYTES]
            stderr_truncated = True
    return proc, stdout_truncated, stderr_truncated


def _parse_response(
    proc: subprocess.CompletedProcess,
    elapsed_ms: int,
    stdout_truncated: bool,
    stderr_truncated: bool,
) -> dict[str, Any]:
    """构造统一 envelope。"""
    success = proc.returncode == 0
    stdout_bytes = proc.stdout or b""
    stderr_bytes = proc.stderr or b""
    stdout_str = stdout_bytes.decode("utf-8", errors="replace")
    stderr_str = stderr_bytes.decode("utf-8", errors="replace")

    # 自适应 JSON 解析
    data: Any = None
    output: str | None = None
    if stdout_str.strip():
        try:
            data = json.loads(stdout_str)
        except json.JSONDecodeError:
            output = stdout_str
    else:
        output = ""

    envelope: dict[str, Any] = {
        "success": success,
        "exit_code": proc.returncode,
        "elapsed_ms": elapsed_ms,
        "data": data,
        "output": output,
    }

    # stderr 仅在 success=false 时透出
    if not success:
        envelope["stderr"] = stderr_str if stderr_str else None
        if stderr_truncated:
            envelope["stderr_truncated"] = True

    if stdout_truncated:
        envelope["truncated"] = True
        envelope["hint"] = (
            f"Output exceeded {MAX_OUTPUT_BYTES // 1024}KB. "
            "Use POST /run/async + GET /jobs/<id> for full output."
        )

    return envelope


def _validate_input(input_dict: dict[str, Any]) -> None:
    """JSON Schema 校验，失败抛 FlashError("validation_failed")。

    没装 jsonschema 时降级到 required 检查 + 字段名白名单。
    """
    try:
        import jsonschema  # type: ignore
        try:
            jsonschema.validate(instance=input_dict, schema=INPUT_SCHEMA)
        except jsonschema.ValidationError as e:
            raise FlashError("validation_failed", f"Schema validation failed: {e.message}") from e
    except ImportError:
        # 降级：只检查 required + 字段名
        required = INPUT_SCHEMA.get("required", [])
        for key in required:
            if key not in input_dict or input_dict[key] in (None, ""):
                raise FlashError(
                    "validation_failed",
                    f"Missing required parameter: '{key}'",
                )

    # 额外：字段名白名单
    for key in input_dict:
        if not _FIELD_NAME_RE.match(key):
            raise FlashError(
                "validation_failed",
                f"Invalid parameter name '{key}'. Allowed: [a-z][a-z0-9_]*",
            )


# ============================================================
# Job store (in-memory + JSONL persistence, 异步任务用)
# ============================================================

JOBS_DIR = FLASH_DATA_DIR / "jobs"
JOBS_DIR.mkdir(parents=True, exist_ok=True)
JOBS_FILE = JOBS_DIR / f"{SKILL_NAME}.jsonl"
JOBS_FILE_MAX_BYTES = 10 * 1024 * 1024  # 10MB
JOBS_FILE_KEEP = 7


class JobStore:
    """Hybrid in-memory + JSONL job store for async execution."""

    def __init__(self):
        self._jobs: dict[str, dict] = {}
        self._lock = threading.Lock()
        self._file_lock = threading.Lock()
        try:
            _max_async = int(os.environ.get("FLASH_MAX_ASYNC", "20"))
            if _max_async < 1:
                _max_async = 20
        except ValueError:
            _max_async = 20
        self._async_semaphore = threading.Semaphore(_max_async)
        self._max_async = _max_async
        self._start_cleanup()

    def create(self, skill_name: str, params: dict) -> str:
        job_id = uuid.uuid4().hex[:12]
        job = {
            "job_id": job_id,
            "skill": skill_name,
            "status": "pending",
            "params": params,
            "created_at": time.time(),
            "result": None,
            "error": None,
            "elapsed_ms": None,
        }
        with self._lock:
            self._jobs[job_id] = job
        return job_id

    def update(self, job_id: str, **kwargs):
        with self._lock:
            if job_id in self._jobs:
                self._jobs[job_id].update(kwargs)
                if kwargs.get("status") in ("completed", "failed"):
                    self._append_jsonl(self._jobs[job_id])

    def get(self, job_id: str) -> dict | None:
        with self._lock:
            job = self._jobs.get(job_id)
        if job is not None:
            return job
        return self._lookup_jsonl(job_id)

    def _append_jsonl(self, job: dict) -> None:
        with self._file_lock:
            try:
                if JOBS_FILE.exists() and JOBS_FILE.stat().st_size >= JOBS_FILE_MAX_BYTES:
                    self._rotate_jsonl()
                line = json.dumps(job, ensure_ascii=False, default=str)
                with JOBS_FILE.open("a", encoding="utf-8") as f:
                    f.write(line + "\n")
            except Exception as e:
                logger.warning(f"JSONL persist failed for {job.get('job_id')}: {e}")

    def _rotate_jsonl(self) -> None:
        for i in range(JOBS_FILE_KEEP, 0, -1):
            src = JOBS_FILE.with_suffix(f".jsonl.{i - 1}" if i > 1 else ".jsonl")
            dst = JOBS_FILE.with_suffix(f".jsonl.{i}")
            if src.exists():
                if dst.exists():
                    dst.unlink()
                src.rename(dst)

    def _lookup_jsonl(self, job_id: str) -> dict | None:
        if not JOBS_FILE.exists():
            return None
        try:
            with JOBS_FILE.open("r", encoding="utf-8") as f:
                lines = f.readlines()
            for line in reversed(lines):
                line = line.strip()
                if not line:
                    continue
                try:
                    record = json.loads(line)
                    if record.get("job_id") == job_id:
                        return record
                except json.JSONDecodeError:
                    continue
        except Exception as e:
            logger.debug(f"JSONL lookup failed: {e}")
        for i in range(1, JOBS_FILE_KEEP + 1):
            rotated = JOBS_FILE.with_suffix(f".jsonl.{i}")
            if not rotated.exists():
                continue
            try:
                with rotated.open("r", encoding="utf-8") as f:
                    for line in reversed(f.readlines()):
                        line = line.strip()
                        if not line:
                            continue
                        try:
                            record = json.loads(line)
                            if record.get("job_id") == job_id:
                                return record
                        except json.JSONDecodeError:
                            continue
            except Exception:
                continue
        return None

    def _start_cleanup(self):
        def _cleanup():
            while True:
                time.sleep(600)
                cutoff = time.time() - 3600
                with self._lock:
                    expired = [
                        jid for jid, j in self._jobs.items()
                        if j.get("created_at", 0) < cutoff
                        and j.get("status") in ("completed", "failed")
                    ]
                    for jid in expired:
                        del self._jobs[jid]

        t = threading.Thread(target=_cleanup, daemon=True)
        t.start()


job_store = JobStore()


# ============================================================
# PID management
# ============================================================

def _write_pid(port: int):
    PID_FILE.write_text(json.dumps({"pid": os.getpid(), "port": port}))


def _clear_pid():
    try:
        PID_FILE.unlink(missing_ok=True)
    except Exception:
        pass


# ============================================================
# FastAPI Application
# ============================================================

@asynccontextmanager
async def _lifespan(app: FastAPI):
    _write_pid(_bound_port)
    logger.info(f"PID file written (PID={os.getpid()}, port={_bound_port})")
    yield
    # 优雅退出：只清 PID 文件，让 uvicorn 自己走完关闭流程
    # （不用 os._exit(0)，否则会绕过 atexit / finally / 日志 flush）
    _clear_pid()
    logger.info("Server stopped, PID file cleared.")


app = FastAPI(
    title=f"{SKILL_NAME} API",
    description=f"skill-to-http-flash v2.0 generated API for {SKILL_NAME}",
    version="2.0.0",
    docs_url="/docs",
    redoc_url="/redoc",
    lifespan=_lifespan,
)

_cors_env = os.environ.get("FLASH_CORS_ALLOW_ORIGINS", "").strip()
_cors_origins = [o.strip() for o in _cors_env.split(",") if o.strip()] if _cors_env else ["*"]
app.add_middleware(
    CORSMiddleware,
    allow_origins=_cors_origins,
    allow_credentials=False,
    allow_methods=["*"],
    allow_headers=["*"],
)
if _cors_origins != ["*"]:
    logger.info(f"CORS allow_origins (from FLASH_CORS_ALLOW_ORIGINS): {_cors_origins}")


# ============================================================
# Request models
# ============================================================

class RunRequest(BaseModel):
    """Run skill request body.

    所有除 timeout_seconds 之外的字段都会被映射到 CLI --key value。
    """
    timeout_seconds: int = Field(
        default=DEFAULT_TIMEOUT,
        ge=1,
        le=3600,
        description="Subprocess execution timeout (seconds)",
    )
    model_config = {"extra": "allow"}


# ============================================================
# API Endpoints
# ============================================================

@app.get("/", response_class=HTMLResponse, include_in_schema=False)
async def root():
    """API guide page."""
    lan_ips = [str(ip) for ip in _get_local_ips() if str(ip) not in ("127.0.0.1", "::1")]
    lan_ip = lan_ips[0] if lan_ips else "localhost"
    schema = "https" if TLS_ENABLED else "http"
    return f"""<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>{SKILL_NAME} API</title>
<style>
body {{ font-family: system-ui, sans-serif; max-width: 720px; margin: 60px auto; padding: 20px; color: #333; }}
h1 {{ font-size: 26px; }}
.status {{ color: #22c55e; font-weight: 600; }}
.card {{ background: #f5f5f5; border-radius: 8px; padding: 20px; margin: 16px 0; }}
.card h3 {{ margin-top: 0; }}
code {{ background: #e8e8e8; padding: 2px 6px; border-radius: 4px; font-size: 13px; }}
pre {{ background: #1e1e1e; color: #d4d4d4; padding: 16px; border-radius: 6px; overflow-x: auto; font-size: 13px; }}
a {{ color: #3b82f6; text-decoration: none; }} a:hover {{ text-decoration: underline; }}
</style></head><body>
<h1>🚀 {SKILL_NAME} API <small style="color:#888;font-size:14px">flash v2.0 / subprocess 直执行</small></h1>
<p class="status">● Running</p>
<p>{SKILL_DESCRIPTION}</p>
<div class="card"><h3>Endpoints</h3>
<table>
<tr><td><code>GET /health</code></td><td>Health check</td></tr>
<tr><td><code>GET /schema</code></td><td>Input parameter schema</td></tr>
<tr><td><code>POST /run</code></td><td>Execute skill (sync, 60s default)</td></tr>
<tr><td><code>POST /run/async</code></td><td>Execute skill (async, no truncation)</td></tr>
<tr><td><code>GET /jobs/&lcub;job_id&rcub;</code></td><td>Poll async job</td></tr>
</table></div>
<div class="card"><h3>Sync</h3>
<pre>curl -X POST {schema}://{lan_ip}:{PORT}/run \\
  -H "Content-Type: application/json" \\
  -d '{json.dumps(_example_payload(), indent=2, ensure_ascii=False)}'</pre></div>
<p style="color:#888;font-size:12px;">Generated {GENERATED_AT} | <a href="/docs">Swagger UI</a></p>
</body></html>"""


def _example_payload() -> dict:
    example = {}
    props = INPUT_SCHEMA.get("properties", {})
    for key, prop in props.items():
        t = prop.get("type", "string")
        if t == "string":
            example[key] = prop.get("default", "example_value")
        elif t in ("number", "integer"):
            example[key] = prop.get("default", 0)
        elif t == "boolean":
            example[key] = prop.get("default", False)
        elif t == "array":
            example[key] = prop.get("default", [])
        elif t == "object":
            example[key] = prop.get("default", {})
    return example


@app.get("/health")
async def health():
    """Probe: entry 文件存在 + interpreter 在 PATH。"""
    entry_ok = False
    entry_reason = ""
    try:
        entry = _resolve_entry()
        entry_ok = entry.exists()
        entry_reason = "ok" if entry_ok else "missing"
    except FlashError as e:
        entry_reason = e.message

    interp = INTERPRETER or "python3"
    interp_ok = shutil.which(interp) is not None

    return {
        "status": "ok" if (entry_ok and interp_ok) else "degraded",
        "skill": SKILL_NAME,
        "uptime_seconds": int(time.time() - _start_time),
        "entry": {
            "path": str(ENTRY_PATH) if ENTRY_PATH else None,
            "ok": entry_ok,
            "reason": entry_reason,
        },
        "interpreter": {
            "name": interp,
            "ok": interp_ok,
        },
    }


@app.get("/schema")
async def get_schema():
    return {
        "skill": SKILL_NAME,
        "description": SKILL_DESCRIPTION,
        "input_schema": INPUT_SCHEMA,
        "timeout_default": DEFAULT_TIMEOUT,
        "entry": ENTRY_REL,
        "interpreter": INTERPRETER,
        "generated_at": GENERATED_AT,
    }


def _check_api_key(request: _Request) -> None:
    if not FLASH_API_KEY:
        return
    key = request.headers.get(API_KEY_HEADER_NAME, "").strip()
    # 恒定时间比较，避免 timing attack
    if not hmac.compare_digest(key, FLASH_API_KEY):
        raise HTTPException(
            status_code=401,
            detail="Unauthorized: invalid or missing API key",
        )


def _extract_params(req: RunRequest) -> dict:
    """提取入参（剔除 timeout_seconds）。"""
    return req.model_dump(exclude={"timeout_seconds"})


def _envelope_error(
    error_type: str,
    message: str,
    elapsed_ms: int,
    http_status: int = 500,
) -> JSONResponse:
    return JSONResponse(
        status_code=http_status,
        content={
            "success": False,
            "exit_code": None,
            "elapsed_ms": elapsed_ms,
            "error_type": error_type,
            "error": message,
            "data": None,
            "output": None,
        },
    )


@app.post("/run")
async def run_sync(req: RunRequest, request: _Request):
    """同步执行：subprocess.run + 60s 默认超时 + 512KB 截断 + 统一 envelope。"""
    _check_api_key(request)
    params = _extract_params(req)
    start = time.time()

    # 1. 入参校验
    try:
        _validate_input(params)
    except FlashError as e:
        elapsed = int((time.time() - start) * 1000)
        logger.warning(f"validation_failed: {e.message}")
        return _envelope_error(e.error_type, e.message, elapsed, http_status=400)

    # 2. 构造 argv
    try:
        argv = _build_argv(params)
    except FlashError as e:
        elapsed = int((time.time() - start) * 1000)
        logger.warning(f"{e.error_type}: {e.message}")
        return _envelope_error(
            e.error_type, e.message, elapsed,
            http_status=500 if e.error_type == "entry_not_found" else 400,
        )

    # 3. subprocess 执行
    try:
        proc, stdout_truncated, stderr_truncated = _run_subprocess(
            argv, req.timeout_seconds, truncate=True,
        )
    except FlashError as e:
        elapsed = int((time.time() - start) * 1000)
        logger.error(f"{e.error_type}: {e.message}")
        http_status = 408 if e.error_type == "timeout" else 500
        return _envelope_error(e.error_type, e.message, elapsed, http_status=http_status)
    except Exception as e:
        elapsed = int((time.time() - start) * 1000)
        logger.exception("internal_error during /run")
        return _envelope_error(
            "internal_error",
            f"{type(e).__name__}: {e}",
            elapsed,
            http_status=500,
        )

    elapsed = int((time.time() - start) * 1000)
    envelope = _parse_response(proc, elapsed, stdout_truncated, stderr_truncated)
    logger.info(
        f"/run exit={proc.returncode} elapsed={elapsed}ms "
        f"truncated={envelope.get('truncated', False)}"
    )
    # exit_code != 0 仍返回 200（业务结果非 HTTP 错误，§7.1）
    return envelope


@app.post("/run/async")
async def run_async(req: RunRequest, request: _Request):
    """异步执行：立即返回 job_id；底层用 subprocess；不截断输出。"""
    _check_api_key(request)
    params = _extract_params(req)

    # 入参校验先做（fail-fast）
    try:
        _validate_input(params)
    except FlashError as e:
        return JSONResponse(
            status_code=400,
            content={"status": "failed", "error_type": e.error_type, "error": e.message},
        )

    if not job_store._async_semaphore.acquire(blocking=False):
        return JSONResponse(
            status_code=429,
            content={
                "status": "failed",
                "error_type": "rate_limited",
                "error": f"Server busy: too many concurrent jobs (limit: {job_store._max_async}). Try again later.",
            },
        )

    job_id = job_store.create(SKILL_NAME, params)
    timeout = req.timeout_seconds

    def _execute():
        start = time.time()
        try:
            job_store.update(job_id, status="running")
            argv = _build_argv(params)
            # 异步：不截断
            proc, _, _ = _run_subprocess(argv, timeout, truncate=False)
            elapsed = int((time.time() - start) * 1000)
            envelope = _parse_response(proc, elapsed, False, False)
            status = "completed" if envelope["success"] else "failed"
            job_store.update(
                job_id,
                status=status,
                result=envelope,
                elapsed_ms=elapsed,
            )
            logger.info(f"Async job {job_id} {status} in {elapsed}ms")
        except FlashError as e:
            elapsed = int((time.time() - start) * 1000)
            job_store.update(
                job_id,
                status="failed",
                error=e.message,
                error_type=e.error_type,
                elapsed_ms=elapsed,
            )
            logger.error(f"Async job {job_id} failed [{e.error_type}]: {e.message}")
        except Exception as e:
            elapsed = int((time.time() - start) * 1000)
            job_store.update(
                job_id,
                status="failed",
                error=f"{type(e).__name__}: {e}",
                error_type="internal_error",
                elapsed_ms=elapsed,
            )
            logger.exception(f"Async job {job_id} internal_error")
        finally:
            job_store._async_semaphore.release()

    threading.Thread(target=_execute, daemon=True).start()

    return {
        "job_id": job_id,
        "status": "pending",
        "poll_url": f"/jobs/{job_id}",
    }


@app.get("/jobs/{job_id}")
async def get_job(job_id: str):
    job = job_store.get(job_id)
    if not job:
        raise HTTPException(status_code=404, detail="Job not found or expired (1-hour memory TTL)")
    return job


# ============================================================
# Main
# ============================================================

_start_time = time.time()
_bound_port: int = 0


def _get_lan_ips() -> list[str]:
    return [str(ip) for ip in _get_local_ips() if str(ip) not in ("127.0.0.1", "::1")]


def main():
    import argparse

    parser = argparse.ArgumentParser(description=f"{SKILL_NAME} API Server (flash v2.0)")
    parser.add_argument("--port", type=int, default=PORT, help=f"Listen port (default: {PORT})")
    parser.add_argument("--host", type=str, default="0.0.0.0", help="Listen host")
    parser.add_argument(
        "action", nargs="?", default="start",
        choices=["start", "status", "stop"],
        help="Action: start (default), status, stop",
    )
    args = parser.parse_args()
    port = args.port

    if args.action == "status":
        if PID_FILE.exists():
            try:
                info = json.loads(PID_FILE.read_text())
                pid = info.get("pid", 0)
                pid_port = info.get("port", 0)
                try:
                    os.kill(pid, 0)
                    print(f"✅ {SKILL_NAME} API running — PID {pid}, port {pid_port}")
                    for ip in _get_lan_ips():
                        proto = "https" if TLS_ENABLED else "http"
                        print(f"   {proto}://{ip}:{pid_port}")
                except ProcessLookupError:
                    print(f"⚠️  PID file exists but process {pid} is dead (stale)")
                    PID_FILE.unlink(missing_ok=True)
                except PermissionError:
                    print(f"✅ {SKILL_NAME} API running — PID {pid}, port {pid_port}")
            except Exception:
                print(f"⚠️  PID file corrupted")
        else:
            print(f"❌ {SKILL_NAME} API not running")
        return

    if args.action == "stop":
        if PID_FILE.exists():
            try:
                info = json.loads(PID_FILE.read_text())
                pid = info.get("pid", 0)
                if pid:
                    print(f"Stopping {SKILL_NAME} API (PID {pid})...")
                    os.kill(pid, signal.SIGTERM)
                    for _ in range(10):
                        time.sleep(1)
                        try:
                            os.kill(pid, 0)
                        except OSError:
                            print("✅ Stopped")
                            PID_FILE.unlink(missing_ok=True)
                            return
                    print("Force killing...")
                    os.kill(pid, signal.SIGKILL)
                    PID_FILE.unlink(missing_ok=True)
                    print("✅ Force stopped")
                    return
            except ProcessLookupError:
                print("Process not found, cleaning up PID file")
                PID_FILE.unlink(missing_ok=True)
                return
            except Exception as e:
                print(f"❌ Failed to stop: {e}")
                return
        else:
            print(f"❌ {SKILL_NAME} API not running (no PID file)")
        return

    # === start ===
    # 1. 启动期 sanity check：entry / interpreter（不阻断，仅 warn）
    try:
        entry = _resolve_entry()
        logger.info(f"Entry resolved: {entry}")
    except FlashError as e:
        logger.warning(f"Entry check failed: {e.message}")
        logger.warning("Server will still start, but /run will return entry_not_found.")

    interp = INTERPRETER or "python3"
    if shutil.which(interp) is None:
        logger.warning(f"Interpreter '{interp}' not found in PATH; /run will fail.")

    # 2. TLS 证书
    if TLS_ENABLED:
        try:
            _generate_cert()
        except ImportError:
            logger.error("cryptography not installed. Install with: pip install cryptography")
            sys.exit(1)
        except Exception as e:
            logger.error(f"Failed to generate certificate: {e}")
            sys.exit(1)

    schema = "https" if TLS_ENABLED else "http"
    lan_ips = _get_lan_ips()
    print()
    print("=" * 56)
    print(f"  ✨  {SKILL_NAME} API  (flash v2.0)")
    print("=" * 56)
    print(f"  Mode   : subprocess direct execution")
    print(f"  Entry  : {ENTRY_REL or '(unset)'}")
    print(f"  Local  : {schema}://localhost:{port}")
    for ip in lan_ips:
        print(f"  LAN    : {schema}://{ip}:{port}")
    print(f"  Docs   : {schema}://localhost:{port}/docs")
    print(f"  Run    : POST {schema}://localhost:{port}/run")
    print(f"  Timeout: {DEFAULT_TIMEOUT}s (default)")
    print("=" * 56)
    if (args.host in ("0.0.0.0", "::")) and not TLS_ENABLED:
        print()
        print("  ⚠️  监听 0.0.0.0 但 TLS 未启用，调用方走明文 HTTP。仅限信任网络使用。")
    print()

    uvicorn_kwargs = dict(
        app=app,
        host=args.host,
        port=port,
        log_level="info",
        timeout_graceful_shutdown=1,
    )
    if TLS_ENABLED:
        uvicorn_kwargs["ssl_certfile"] = str(CERT_FILE)
        uvicorn_kwargs["ssl_keyfile"] = str(KEY_FILE)
    config = uvicorn.Config(**uvicorn_kwargs)
    server = uvicorn.Server(config)

    global _bound_port
    _bound_port = port
    try:
        server.run()
    except OSError as e:
        if "address already in use" in str(e).lower() or e.errno == 98:
            logger.error(f"Port {port} is already in use. Choose a different port.")
            raise
    finally:
        _clear_pid()


if __name__ == "__main__":
    main()
